name: dartlero_category_links
version: 0.0.6
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: A model with 2 concepts that uses dartlero. A web application with web components that use the model.
homepage: http://ondart.me/
dependencies:
  browser: any
  web_ui: any
  dartlero:
    git: git://github.com/dzenanr/dartlero.git
